name: example
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_bottom_navigation_image: 1.0.0


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - search.png
    - settings.png
    - sydney-opera-house.png
    - user.png
